name: Build & Deploy Order Service

on:
  push:
    branches: [ main ]
    paths:
      - services/order-service/**
      - k8s-manifests/base/services/order/**

jobs:
  order-ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit tests
        run: |
          cd services/order-service
          pip install -r requirements.txt
          export PYTHONPATH=$(pwd)
          pytest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push Image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }}
          docker build -t $IMAGE services/order-service
          docker push $IMAGE

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}

      - name: Ensure namespace exists
        run: |
          kubectl get ns devops-demo || kubectl create ns devops-demo

      - name: Deploy Order Service
        run: |
          kubectl set image deployment/order-service \
            order-service=${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }} \
            -n devops-demo

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/order-service -n devops-demo

