name: Build & Deploy Order Service

on:
  push:
    branches: [ main ]
    paths:
      - services/order-service/**
      - k8s-manifests/base/services/order/**

jobs:
  order-ci-cd:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v4

      # ---------- CI ----------
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit tests
        run: |
          cd services/order-service
          pip install -r requirements.txt
          pytest

      # ---------- Azure Login ----------
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      # ---------- Build & Push ----------
      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push Image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }}
          docker build -t $IMAGE services/order-service
          docker push $IMAGE

      # ---------- AKS Context ----------
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      # ---------- CD ----------
      - name: Ensure namespace exists
        run: |
          kubectl get ns devops-demo || kubectl create ns devops-demo

      - name: Deploy Order Service
        run: |
          kubectl set image deployment/order-service \
            order-service=${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }} \
            -n devops-demo

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/order-service -n devops-demo

