name: Build & Deploy User Service

on:
  push:
    branches: [ main ]
    paths:
      - services/user-service/**
      - k8s-manifests/base/services/user/**

jobs:
  user-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- CI ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run unit tests
        run: |
          cd services/user-service
          pip install -r requirements.txt
          pytest

      # ---------- BUILD ----------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ github.sha }}
          docker build -t $IMAGE services/user-service
          docker push $IMAGE

      # ---------- CD ----------
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy User Service
        run: |
          kubectl set image deployment/user-service \
            user-service=${{ secrets.ACR_LOGIN_SERVER }}/user-service:${{ github.sha }} \
            -n devops-demo

